name: technest
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  flutter_text_box: ^0.0.1
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/file.png
    - assets/file.svg
    - assets/google.png
    - assets/twitter.png
    - assets/facebook.png

  #fonts:
  #   - family: Funnelsans
